services:
  claude_bot:
    image: maxfraieho/claude-code-telegram:latest
    container_name: claude-code-bot-prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./target_project:/app/target_project
    working_dir: /app
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0) if __import__('src.main') else sys.exit(1)"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data: